
# To build, run from inside the JuliaML directory:
#     git checkout dev
#     git pull
#     mkdocs build --clean
# Add files, commit, then push:
#     git push origin dev
# Push just the site directory to the master branch
#     git subtree push --prefix site origin master

site_name: 'JuliaML'
site_author: 'JuliaML Members and Contributors'
site_description: 'Learning from Data with Julia'
site_url: 'https://JuliaML.github.io'

repo_name: 'GitHub'
repo_url: 'https://github.com/JuliaML/Learn.jl'

copyright: 'Copyright &copy; 2015-2017 JuliaML Members'

pages:
  - Home: index.md
  - Design: design.md
  - Contributing: contributing.md

docs_dir: 'docs'

theme: material

extra:
  author:
    github: 'JuliaML'
  palette:
    primary: 'blue grey'
    accent: 'grey'
  logo: 'images/juliaml_logo.png'

markdown_extensions:
    - admonition
    - codehilite(css_class=code)
    # - mdx_math:
    #     enable_dollar_delimiter: True

extra_javascript: [
     'mathjax-config.js',
     'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
]
